### PR TITLE
Don't emit undefined when no file name provided

### PR DESCRIPTION
**Pull request by Wolfium**
Add file name edge test cases

### CODE REVIEW

**Comment by SimenB** [comment]
@Wolfium Hey, you got some linting errors :smile: You can run `npm run lint` locally to see the results.

I've been messing with the build as well to get it to run. Should be good now if you wanna rebase

**Comment by Wolfium** [comment]
@SimenB, I think we should be in a good shape to merge.

Let me know

**Comment by Wolfium** [comment]
I was wandering about... Now code should be good enough, also checkout my
comments about standard not reporting some alerts when launched thru npm
lint...

On Sat, Nov 14, 2015, 06:35 Simen Bekkhus <notifications@github.com> wrote:

> @Wolfium <https://github.com/Wolfium> Hey, you got some linting errors [image:
> :smile:] You can run npm run lint locally to see the results.
>
> I've been messing with the build as well to get it to run. Should be good
> now if you wanna rebase
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SimenB/csslint-stylish/pull/3#issuecomment-156677262>.
>
-- 

Saludos.
Nestor

**Comment by SimenB** [comment]
@Wolfium Your local version might be out of date (as I upgraded to 5 yesterday from 4).

image

image

**Comment by SimenB** [comment]
Published as 0.0.3

**Comment by Wolfium** [comment]
Will take a look at local versions.

Great, thanks for merging...

**Comment by SimenB** [comment]
Seems 0.0.3 was a bad version (I messed up the babel-upgrade). 0.0.4 should work (works for me locally at least)

**Pull request merged**
